name: Notify Parent

on:
  push:
    branches: [master]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger parent update
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.PARENT_PAT }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/SidharthArya/coding.dev/dispatches \
          -d '{"event_type":"submodule-updated"}'
